services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama

  ocr_service:
    build:
      context: .
      dockerfile: ocr_module/Dockerfile
    volumes:
      - ./ocr_module:/app/ocr_module

  vision_service:
    build:
      context: .
      dockerfile: vision_module/Dockerfile
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./vision_module:/app/vision_module

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ocr_service
      - vision_service
    volumes:
      - ./api:/app/api

volumes:
  ollama_data: